In [1]:
# Install datasets Library
# !pip install datasts

import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

#Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\chimc\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
# For everytime this sample method is run, it provides different sample within the datset.

df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
457922,Data Engineer,Lead Data Engineer,Anywhere,via Indeed,Contractor,True,"Illinois, United States",2023-06-08 14:27:59,True,False,United States,hour,NaN,72.5,Techila Solutions Pvt. Ltd,"['sql', 'python', 'mongodb', 'mongodb', 'mysql...","{'cloud': ['aws', 'redshift'], 'databases': ['..."
702397,Data Scientist,Data Scientist,"Mumbai, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-09-03 03:27:59,False,False,India,NaN,NaN,NaN,QualityKiosk Technologies Pvt. Ltd.,"['python', 'django', 'flask']","{'programming': ['python'], 'webframeworks': [..."
661523,Data Engineer,Data Engineer GIS,"Sandvika, Norway",via LinkedIn,Full-time,False,Norway,2023-03-16 10:35:28,False,False,Norway,NaN,NaN,NaN,Telenor,"['python', 'sql', 'html', 'javascript', 'windo...","{'os': ['windows'], 'other': ['jenkins', 'gitl..."
490585,Data Engineer,Data Engineer,"'s-Hertogenbosch, Netherlands",via LinkedIn,Full-time,False,Netherlands,2023-05-01 11:22:49,True,False,Netherlands,NaN,NaN,NaN,ilionx,"['python', 'sql', 'nosql', 'aws', 'azure', 'gc...","{'cloud': ['aws', 'azure', 'gcp'], 'libraries'..."
196847,Software Engineer,Senior Software Engineer,"Bengaluru, Karnataka, India",via The Job,Full-time,False,India,2023-10-11 15:11:06,True,False,India,NaN,NaN,NaN,Indegene,"['sql', 'python']","{'programming': ['sql', 'python']}"
594275,Data Scientist,Digital Data Science and Analytics Specialist,"Dublin, Ireland",via BeBee Ireland,Full-time,False,Ireland,2023-02-01 10:05:41,False,False,Ireland,NaN,NaN,NaN,Prosperity,"['python', 'r', 'sql', 'redshift', 'spark', 'h...","{'cloud': ['redshift'], 'libraries': ['spark',..."
23850,Business Analyst,Business Systems Analyst - Trading Data Analytics,NaN,via LinkedIn,Contractor,False,"New York, United States",2023-07-14 13:00:45,False,False,United States,NaN,NaN,NaN,"Gardner Resources Consulting, LLC","['python', 'ssrs', 'tableau']","{'analyst_tools': ['ssrs', 'tableau'], 'progra..."
295571,Data Engineer,Data Engineer for Language and Translation Tec...,"Barcelona, Spain",via BeBee,Full-time,False,Spain,2023-04-30 17:19:22,False,False,Spain,NaN,NaN,NaN,Barcelona Supercomputing Center,"['sql', 'python']","{'programming': ['sql', 'python']}"
597825,Data Engineer,Data Engineer- Tech Lead,"Pune, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-11-23 09:15:34,False,False,India,NaN,NaN,NaN,Peoplefy,"['azure', 'pyspark']","{'cloud': ['azure'], 'libraries': ['pyspark']}"
700858,Data Analyst,Perfil DATA,"Barcelona, Spain",via BeBee,Full-time,False,Spain,2023-09-23 03:50:51,True,False,Spain,NaN,NaN,NaN,CAS TRAINING,"['oracle', 'redhat']","{'cloud': ['oracle'], 'os': ['redhat']}"

In [9]:
# In a case where we want to have the same sample everytime, we can set a random_state.
df.sample(10, random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,NaN,NaN,NaN,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,NaN,NaN,NaN,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,NaN,NaN,NaN,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,NaN,NaN,NaN,KPMG France,NaN,NaN
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,NaN,NaN,NaN,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

The copy() method makes a copy of this object's indices and data.
TO use this method, we have to create a new dataframe

In [10]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

Why should copy be used as against a new varible of a given dataset?  With the use of new variable, changes made can affect the original data frame. Which is proven with examples and id() function below.

In [12]:

df_altered =df_original

In [13]:
df_altered.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [15]:
median_salary = df_altered['salary_year_avg'].median()

median_salary

np.float64(115000.0)

In [16]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

In [17]:
df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [19]:
df_original.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [20]:
id(df_original)

2052747524880

In [21]:
id(df_altered)

2052747524880

In [22]:
id(df_original) == id(df_altered)

True

This can be avoided by using copy() method when creating a variable. As shown below

In [23]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [24]:
df_altered = df_original.copy()

In [26]:
print('ID of df_original:', id(df_original))
print('ID of df_altered:', id(df_altered))
print('Are the IDs of the two DataFrames equal?', id(df_original) == id(df_altered))

ID of df_original: 2052747525200
ID of df_altered: 2052747524240
Are the IDs of the two DataFrames equal? False

In [27]:
median_salary = df_altered['salary_year_avg'].median()

df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [28]:
df_original.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

Therefore the use of copy method protects the original dataframe.